Repository fortran-lang/fpm, pull requests merged in 2021-09, with the labels that each got.

#562 Add new distributions where fpm is available to README
  README.md
Labels: documentation

#563 Add workflow to create single source fpm version
  .github/workflows/release.yml
  ci/single-file-gfortran.sh
  ci/single-file.patch
Labels: automation

#564 Separate upload stage in CI testing
  .github/workflows/CI.yml
Labels: automation

#578 help text was truncated
  src/fpm_command_line.f90
Labels: documentation

#584 Actually read environment variables
  src/fpm_command_line.f90
Labels: bug
